### PR TITLE
Change PR Checklist

### PR DESCRIPTION
**Pull request by jonnyarnold**
- Split checklist into Author and Reviewer sections, to be explicit who is responsible for the box-ticking.
- Greater emphasis on testing and understandability.

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
*If you're new, read the [guidelines](https://github.com/reevoo/guidelines/blob/master/pull_requests.md).*

Good code is **tested**, **easy to understand** and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

- [ ] Code has been reviewed.
- [ ] Description explains what you have done and why.
- [ ] Tests are green on CI (or pulled/tested on another machine).
- [ ] Documentation has been created or updated.

**Comment by errm** [comment]
Looks like a good improvement...

**Comment by Antti** [comment]
What about other code qualities? Or do we only care if it's easy to understand?

**Comment by jonnyarnold** [comment]
@Antti What else would you propose?

**Comment by richardbatty** [comment]
LGTM

**Pull request merged**
