### PR TITLE
Fetch production github key from ENV

### PR DESCRIPTION
**Pull request by lpil**
https://github.com/reevoo/samuel/issues/19

http://12factor.net/

### CODE REVIEW

**Comment by lpil** [comment]
Jonny says:

> Can we get something .env-like?

Louis says:

What's the advantage of .env? I've not played with it.

**Comment by jonnyarnold** [comment]
In development I want to be able to run `mix` with the Github access token on my machine. Rather than do `GITHUB_ACCESS_KEY=key-key-key mix`, I want to just be able to run `mix`, specify my environment in a .env file, and go.

This becomes especially important when we get more environment variables.

**Comment by lpil** [comment]
I think there's an established way to do this sort of thing with OTP, but I'm not sure what it is yet. I don't think .env really fits in with OTP + mix

**Comment by lpil** [comment]
```elixir
System.get_env("MY_VAR") || Application.get_env(:myapp, :my_var) || some_default
```

This looks sensible.

**Comment by jonnyarnold** [comment]
Looks like a macro to me ;)

**Comment by lpil** [comment]
Possibly. Happy to put this into master?

**Comment by jonnyarnold** [comment]
Yep, fire away.

**Comment by lpil** [comment]
Rebased it, but github didn't notice. Guess it's a bug on their end.

**Pull request closed without merging**
